### ISSUE TITLE
Mobile menu toggle for navigation overlaps with content (especially in Mail & Contacts)

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/groupware#2]
mail application in the mobile version from this annoying overlap of the 3 lines that make the menu open with the first readable email.

I attach screenshot

![63912980-e1f8dc00-ca2e-11e9-9b25-7bf53d05005c](https://user-images.githubusercontent.com/35575744/63923270-889ca700-ca46-11e9-8123-4217431178d1.png)

## Work packages

- [x] https://github.com/nextcloud/calendar/issues/5121
- [x] https://github.com/nextcloud/contacts/pull/2711
- [x] https://github.com/nextcloud/mail/pull/6774

**Comment by marcoambrosini** [comment]
Issue transferred to groupware because that's where it is most present still. So for now it will be responsibility of app developers to make room for the toggle. The suggested solution is to use a top-bar like in talk, deck and files. At some point it would probably make sense to have a top-bar ported to the vue library I guess.

So next items are:

- [ ] Add info about how to handle this in the design documentation; [opened issue here ](https://github.com/nextcloud/documentation/issues/7521)
- [ ] Fix toggle overlap in Calendar
- [ ] Fix toggle overlap in Mail
- [ ] Fix toggle overlap in Contacts

**Comment by dartcafe** [comment]
Appstore has the same issue.

**Comment by andyxheli** [comment]
@marcoambrosini There's also an issue on 
![image](https://user-images.githubusercontent.com/59488153/142247628-072b73f5-f644-42c1-a8be-f6ba5e175b47.png)
![image](https://user-images.githubusercontent.com/59488153/142247643-ea8d498f-8b17-4ce1-9d4d-e9f8fe89d40c.png)

**Comment by marcoambrosini** [comment]
@andyxheli this is not related to the navigation toggle, but yes please! You can goa ahead and open an issue about the copy link button in the server repo :)

**Comment by andyxheli** [comment]
@marcoambrosini Thank you!

**Comment by Valdnet** [comment]
You should also take into account this reported [issue](https://github.com/nextcloud/server/issues/31069) with the application list.

**Comment by reos-rcrozier** [comment]
What about a solution like this. The menu button is made very thin and made part of the menu sidebar (or really a separate div or whatever it is that can't actually contain any content from the menu), and the menu only collapses to the thickness of the button. You permanently loose the thickness of the button from the available space, but it will work for any app.
![image](https://user-images.githubusercontent.com/91322120/157688572-4217bb79-3316-4544-8cb4-6384cbfc39c2.png)

**Comment by Hrishkesh** [comment]
Hi there, I'm facing a similar problem over toggle menu overlay as I attach the screen shot below.
I'm using my app called VDPP as a plugin it worked well for the version 20.0.2 (left side of the image) and there is a toggle menu overlay for the next recurring versions  like (21.0.9) .


Also I tried to adjust the parameter called padding as indicated in the screenshot, then it works fine for the time being.

As I see,  is the problem with the nextcloud or my app ??
![Screenshot_nextcloud](https://user-images.githubusercontent.com/39919077/167970704-e1d76477-9bb4-4323-8739-9080769f096b.jpg)

**Comment by tcitworld** [comment]
Reopened for calendar & contacts

**Comment by jancborchardt** [comment]
This has been fixed nicely with Nextcloud Hub 3 (25) already in both Mail and Contacts:
![image](https://user-images.githubusercontent.com/925062/227916921-23f5881e-f8bf-47e6-b1e1-940b759e9592.png)

**Comment by ChristophWurst** [comment]
Not for Calendar

**Comment by st3iny** [comment]
I'm afraid there are only two ways of fixing this for calendar:
1. Increase header height to accommodate for the toggle button (~44px so we need 52px for the header). This has the disadvantage of reducing the available vertical space for the calendar grid.
2. Decrease toggle button top margin (and height) to make it fit in the existing grid header. This won't affect the vertical space of the calendar grid but will break visual consistency with other apps as the button is a bit higher (and narrower).

**Comment by dartcafe** [comment]
IMHO this toggle should still not be positioned inside the app container.

In the end the positioning problem of this toggle is just delegated to every app developer.

**Comment by crobarcro** [comment]
I still think something like [my solution](https://github.com/nextcloud/groupware/issues/2#issuecomment-1064154874) would be a better way to go. It also, as the previous poster mentions, ensures app devs don't have to deal with it (which inevitably means a better look and feel for all apps).

**Comment by st3iny** [comment]
Thanks for your input :)

What should we do about the list view? We could either add a top margin to the first entry to move the whole list down. Or we could add a left margin to the first entry to make room (horizontally) for the toggle.

![list-view](https://user-images.githubusercontent.com/1479486/229125710-c6f016db-f500-4ae5-bf8b-a9ec4461139f.png)

cc @jancborchardt

**Comment by dartcafe** [comment]
> In practice it also works with pretty much all apps

Yes, because devs fiddled around that toggle to avoid overlapping on desktop view, mobile view, when scrolling, and on and on.  And after all oviously even the core apps still have problems. And the next issue will appear (i.e. alignment), when it lcomes to design changes.

There were several proposals how to get rid of this dependency, but the problem still exists. 
This is still my favorite (mockup):

expanded | collapsed
-|-
![grafik](https://user-images.githubusercontent.com/26707476/229281446-bf1d3daf-b407-4b02-8cca-7d7aa11505cf.png)|![grafik](https://user-images.githubusercontent.com/26707476/229281461-1b8a548d-7157-4120-b135-0838204985a0.png)

**Comment by ChristophWurst** [comment]
@jancborchardt @marcoambrosini @nimishavijay please provide us with a mockup for Calendar https://github.com/nextcloud/groupware/issues/2#issuecomment-1491892086. It seems to be the trickiest of the three groupware apps.

**Comment by szaimen** [comment]
> @jancborchardt @marcoambrosini @nimishavijay please provide us with a mockup for Calendar [#2 (comment)](https://github.com/nextcloud/groupware/issues/2#issuecomment-1491892086).

Something like this would be preferred from my side: 

https://github.com/nextcloud/groupware/assets/42591237/b55f96bb-5c68-4e18-bdf6-67a361836c3c

(made by @ya-d in https://github.com/nextcloud/groupware/issues/2#issuecomment-774341128)

WDYT @nextcloud/designers ?

**Comment by raimund-schluessler** [comment]
> Yes the only solutions seem to be either a vertical column or a top row. I think a row works best because we can nicely lay out some buttons that allow us to use calendar with the left sidebar collapsed.
> 
> for example: <img alt="Screenshot 2023-06-12 at 16 10 32" width="1007" src="https://user-images.githubusercontent.com/26852655/245073729-d198c2bd-8b9b-4222-b020-e7b8cb2e3698.png">
> 
> @dartcafe the toggle being inside or outside the navigation is a separate issue. I agree with you that it should be inside but I'd prefer it to stay in the same place (top-left) always, regardless of whether the navigation is collapsed or expanded.

I like this approach. One could then even expand the view switcher and show `Day|Week|Month|List` in the middle of the header, like Apple does it:
![grafik](https://github.com/nextcloud/groupware/assets/2496460/af2f4e6d-8199-4073-82a4-e2926706b115)

**Comment by nimishavijay** [comment]
Looks good in the mockups @marcoambrosini! :) 

A case to keep in mind is the mobile view in general, there is not as much vertical space available, and in for eg. week view, almost a third of screen is taken up by the browser bar, Nextcloud header bar, the new button row, calendar headers and all day events. all of which can't be scrolled away. Perhaps in mobile we should take a different approach and indent the calendar header text to avoid overlap with the toggle. What do you think?

![image](https://github.com/nextcloud/groupware/assets/52440189/6d653023-2a0a-4908-bb00-a2ea3e0bef49)

**Comment by dartcafe** [comment]
> @dartcafe the toggle being inside or outside the navigation is a separate issue. I agree with you that it should be inside but I'd prefer it to stay in the same place (top-left) always, regardless of whether the navigation is collapsed or expanded.

In the case of the toggle (which comes from the components) I am just arguing from the view of an app developer. So I'm not talking about the calendar or any other particular app. This leadds to a task for any app devloper, who uses the vue components and especially when it comes to the sidebar.

I repeat myself: 
> In practice it also works with pretty much all apps

Yes because every app deloper solved this problem individually. That costs much time, nerves and ressources. Count the discussions in the Mail and Calendar app alone and for how long this issue gets discussed. Therefore I plead for a centralized solution inside the vue components. Or at least a style guide (implement in a row or in a column, what to do with the whitespace, and so on).

I know this is no master issue, but (again) for an app developer it was a pain for a very long time.

**Comment by marcoambrosini** [comment]
@nimishavijay I would skip creating an exception like that for each calendar view on mobile (e.g. how do we solve it in list view?). 

@dartcafe even if the button is within the boundaries of the sidebar, when the sidebar is collapsed we're faced with the same content overlap issue. That's why I think that the toggle placement (within or without sidebar boundaries) is orthogonal to this particular issue.

**Comment by szaimen** [comment]
> @nimishavijay I would skip creating an exception like that for each calendar view on mobile (e.g. how do we solve it in list view?).

I agree 👍

**Comment by dartcafe** [comment]
> @dartcafe even if the button is within the boundaries of the sidebar, when the sidebar is collapsed we're faced with the same content overlap issue.

@marcoambrosini That's why I made the proposal to collaps the sidebar to a [visible vertical panel](https://github.com/nextcloud/groupware/issues/2#issuecomment-1492920373).

I don't think it is wise to separate the problem of the overlapping toggle from the view in the groupware apps. The toggle comes from the vue components and is also used in many other apps. 

Situation A: The groupware apps solve it by rearranging the app container due tu the fact, that the toggle is inside that container. This way there will be no more need to think about the toggle and change the vue components because: "Problem is solved." But the pain for all other devs stays. And I hardly doubt, that this will get priority afterwards.

Situation B: The groupware apps solve it by rearranging the app container due tu the fact, that the toggle is inside that container. Afterwards (some day) the toggle issue will be solved within the vue components to ease the devs pain. Then you have to start over to fix the groupware apps. 

This makes me think, that it would be better so get a central solution for all apps, that use the sidebar components. My proposal also comes from some discussions about making the sidebar visible also in collapsed mode for a better accessibility of the sidebar entries. Last but not least it is an UX issue, as long as every app uses its own solution. 

BTW: The  calendar view on mobile in portrait view is of limited value IMHO. Shouldn't it not just offer the agenda or day view instead of a week/month view? At least this is how thw calendar apps on mobiles solve that. Grids then are only displayed in landscape mode.

**Comment by dartcafe** [comment]
BTW: The  calendar view on mobile in portrait view is of limited value IMHO. Shouldn't it not just offer the agenda or day view instead of a week/month view? At least this is how thw calendar apps on mobiles solve that. Grids then are only displayed in landscape mode.

**Comment by szaimen** [comment]
> BTW: The calendar view on mobile in portrait view is of limited value IMHO. Shouldn't it not just offer the agenda or day view instead of a week/month view? At least this is how thw calendar apps on mobiles solve that. Grids then are only displayed in landscape mode.

At least on Android there are many apps that offer week/month view even in portrait mode and are still very useful. So I'd say it still makes sense to alao offer it in our calendar.

**Comment by dartcafe** [comment]
> At least on Android there are many apps that offer week/month view even in portrait mode and are still very useful. So I'd say it still makes sense to alao offer it in our calendar.

Interesting. Curious, how that looks. Thanks for the hint.

**Comment by ChristophWurst** [comment]
- [ ] To do: mockups and design specs

**Comment by jancborchardt** [comment]
Fixed now with https://github.com/nextcloud/calendar/pull/5391

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/pull/5391#issuecomment-1665542125

**Comment by jancborchardt** [comment]
The additional feedback by @raimund-schluessler was now fixed for good by @szaimen in https://github.com/nextcloud/calendar/pull/5475 :)

**Comment by raimund-schluessler** [comment]
> The additional feedback by @raimund-schluessler was now fixed for good by @szaimen in [nextcloud/calendar#5475](https://github.com/nextcloud/calendar/pull/5475) :)

Well....

https://github.com/nextcloud/calendar/pull/5475#issuecomment-1730188885
