### ISSUE TITLE
Standardize usage of labels, milestones and automations

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupware#9]
Our apps all have some special handling for their labels, milestones and some automations.

Examples
* Calendar has *enhancement-proposed* and *enhancement-approved* labels. No other app has that
* Mail has a bot that closes stale tickets after some time. No other app has that
* Contacts branches and milestones are chaos.

## Todo

* [x] Unify label usage
  * https://docs.nextcloud.com/server/stable/developer_manual/prologue/development_process.html#the-labels
  * https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html#labels
  * Use common descriptions from documentation
  * Unify common labels colors
* [x] Unify milestone usage (needs documentation) https://github.com/nextcloud/groupware/pull/19
* [ ] Unify automations (possibly needs documentation) https://github.com/nextcloud/groupware/pull/21
  * Calendar uses https://github.com/nextcloud/calendar/blob/main/.github/no-response.yml (no response bot)
  * Contacts uses https://github.com/nextcloud/contacts/blob/main/.github/stale.yml (stale bot)
  * Mail uses https://github.com/nextcloud/mail/blob/main/.github/stale.yml (stale bot)
  * https://github.com/actions/stale looks promising
* [x] Add CalDAV and CardDAV labels in server

**Comment by ChristophWurst** [comment]
Note for the automation: close tickets in two steps. First announce that we will close if there is no more activity, then we close.

**Comment by ChristophWurst** [comment]
Meeting notes added as https://github.com/nextcloud/groupware/blob/main/meetings/2021-12-17_repo_milestone_label_cleanup.md

**Comment by ChristophWurst** [comment]
These are our organization defaults for new repos. They look clean.

![Screenshot 2021-12-29 at 11-42-44 Build software better, together](https://user-images.githubusercontent.com/1374172/147654063-a97c9703-3ec8-4986-b61a-5e81e58ac395.png)

**Comment by juliushaertl** [comment]
Just in case: there is also https://github.com/nextcloud/github_helper/tree/master/label-updater around which could be used to unify those on existing repositories as well
